[
functions
]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["pdf-lib"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

